PivotX\CoreBundle\Entity\Entry:
  type: entity
  table: entry
  indexes:
    resource_index:
      columns:
        - resource_id
  fields:
    id:
      type: integer
      length: null
      precision: 0
      scale: 0
      nullable: false
      unique: false
      id: true
      generator:
        strategy: IDENTITY
    resource_id:
      type: integer
      length: null
      precision: 0
      scale: 0
      nullable: true
      unique: false
    publicid:
      type: string
      length: 64
      precision: 0
      scale: 0
      nullable: true
      unique: false
    date_created:
      type: datetime
      length: null
      precision: 0
      scale: 0
      nullable: false
      unique: false
      auto_entity:
        timestampable:
          on: create
    date_modified:
      type: datetime
      length: null
      precision: 0
      scale: 0
      nullable: false
      unique: false
      auto_entity:
        timestampable:
          on: update
    viewable:
      type: integer
      length: null
      precision: 0
      scale: 0
      nullable: false
      unique: false
    publish_state:
      type: string
      length: 32
      precision: 0
      scale: 0
      nullable: false
      unique: false
      auto_entity:
        publishable:
          type: state
    publish_on:
      type: datetime
      length: null
      precision: 0
      scale: 0
      nullable: true
      unique: false
      auto_entity:
        publishable:
          type: publish
    depublish_on:
      type: datetime
      length: null
      precision: 0
      scale: 0
      nullable: true
      unique: false
      auto_entity:
        publishable:
          type: depublish
    version:
      type: string
      length: 32
      precision: 0
      scale: 0
      nullable: false
      unique: false
  oneToMany:
    languages:
      targetEntity: EntryLanguage
      cascade:
        - remove
      mappedBy: entry
      inversedBy: null
      orphanRemoval: true
      orderBy: null
      pivotx:
        multilingual:
          field: language
  lifecycleCallbacks: {  }
